from __future__ import annotations

import io
import json
import zipfile
from datetime import datetime, timedelta, timezone

from app.catalogs import ICEYE_PUBLIC_PROFILE
from app.integrations.access.models import AccessPathPoint, GeometricAccessWindow
from app.integrations.orbits import PublicOrbitRecord, SatelliteFamily, TrackedSatellite
from app.integrations.stk_validation import (
    build_stk_validation_bundle,
    compare_access_intervals,
    compare_aer_samples,
    parse_stk_access_report,
    parse_stk_aer_report,
)
from app.models.enums import ObservationSide, RequestMode, SensorType
from app.models.geometry import PointGeometry
from app.models.request import ObservationRequest


def _window(
    *,
    window_id: str = "ACCESS-TEST-SAR-01-SPOT-001",
    start: datetime | None = None,
) -> GeometricAccessWindow:
    start = start or datetime(2026, 7, 16, 12, 0, tzinfo=timezone.utc)
    path = (
        AccessPathPoint(
            timestamp_utc=start,
            satellite_latitude_deg=0.0,
            satellite_longitude_deg=0.0,
            satellite_altitude_km=500.0,
            off_nadir_angle_deg=0.0,
            incidence_angle_deg=0.0,
            sun_elevation_deg=None,
        ),
        AccessPathPoint(
            timestamp_utc=start + timedelta(seconds=60),
            satellite_latitude_deg=0.0,
            satellite_longitude_deg=0.0,
            satellite_altitude_km=500.0,
            off_nadir_angle_deg=0.0,
            incidence_angle_deg=0.0,
            sun_elevation_deg=None,
        ),
    )
    return GeometricAccessWindow(
        window_id=window_id,
        request_id="REQ-TEST",
        satellite_id="SAR-01",
        satellite_name="ICEYE-X99",
        norad_cat_id=65001,
        family=SatelliteFamily.ICEYE,
        sensor_type=SensorType.SAR,
        mode_id="MODE-SAR-ICEYE-SPOT",
        mode_name="Spot",
        start_utc=start,
        end_utc=start + timedelta(seconds=60),
        peak_utc=start + timedelta(seconds=30),
        observation_side=ObservationSide.NADIR,
        duration_s=60.0,
        coverage_ratio=1.0,
        minimum_off_nadir_deg=0.0,
        maximum_off_nadir_deg=0.0,
        minimum_incidence_angle_deg=0.0,
        maximum_incidence_angle_deg=0.0,
        peak_sun_elevation_deg=None,
        orbit_epoch_utc=start - timedelta(hours=1),
        sample_count=2,
        path=path,
    )


def _request() -> ObservationRequest:
    return ObservationRequest(
        request_id="REQ-TEST",
        name="Test",
        geometry=PointGeometry(coordinates=(0.0, 0.0)),
        priority=8,
        earliest_start_utc=datetime(2026, 7, 16, 11, tzinfo=timezone.utc),
        latest_end_utc=datetime(2026, 7, 16, 13, tzinfo=timezone.utc),
        request_mode=RequestMode.SINGLE,
        requested_sensor_types=[SensorType.SAR],
        max_resolution_m=1.0,
        minimum_coverage_ratio=1.0,
        max_incidence_angle_deg=40.0,
        max_off_nadir_deg=45.0,
    )


def _satellite() -> TrackedSatellite:
    epoch = datetime(2026, 7, 16, 11, tzinfo=timezone.utc)
    return TrackedSatellite(
        slot_id="SAR-01",
        family=SatelliteFamily.ICEYE,
        record=PublicOrbitRecord(
            object_name="ICEYE-X99",
            object_id="2026-001A",
            norad_cat_id=65001,
            epoch_utc=epoch,
            mean_motion_rev_per_day=15.2,
            eccentricity=0.001,
            inclination_deg=97.8,
            raan_deg=10.0,
            argument_of_pericenter_deg=0.0,
            mean_anomaly_deg=0.0,
            bstar=0.0,
            mean_motion_dot=0.0,
            mean_motion_ddot=0.0,
            element_set_no=1,
            rev_at_epoch=1,
            raw_omm={
                "OBJECT_NAME": "ICEYE-X99",
                "NORAD_CAT_ID": 65001,
                "EPOCH": epoch.isoformat(),
                "MEAN_MOTION": 15.2,
                "ECCENTRICITY": 0.001,
                "INCLINATION": 97.8,
                "RA_OF_ASC_NODE": 10.0,
                "ARG_OF_PERICENTER": 0.0,
                "MEAN_ANOMALY": 0.0,
            },
        ),
    )


def test_parse_stk_access_report_with_standard_utcg_header() -> None:
    payload = """Access Number,Start Time (UTCG),Stop Time (UTCG),Duration (sec)
1,16 Jul 2026 12:00:05.000,16 Jul 2026 12:01:03.000,58
"""
    report = parse_stk_access_report(payload)

    assert len(report.intervals) == 1
    assert report.intervals[0].duration_s == 58.0
    assert report.intervals[0].start_utc.tzinfo == timezone.utc
    assert report.detected_columns["start"] == "Start Time (UTCG)"


def test_parse_stk_access_report_accepts_semicolon_and_preamble() -> None:
    payload = """STK Report
Generated by test
Access Number;Start Time (UTCG);Stop Time (UTCG);Duration (sec)
1;16 Jul 2026 12:00:00;16 Jul 2026 12:01:00;60,0
"""
    report = parse_stk_access_report(payload)

    assert report.delimiter == ";"
    assert report.intervals[0].duration_s == 60.0


def test_compare_access_intervals_reports_signed_errors_and_overlap() -> None:
    window = _window()
    report = parse_stk_access_report(
        """Access Number,Start Time (UTCG),Stop Time (UTCG),Duration (sec)
1,16 Jul 2026 12:00:05,16 Jul 2026 12:01:03,58
"""
    )
    result = compare_access_intervals((window,), report.intervals, tolerance_s=30)

    assert len(result.matched) == 1
    match = result.matched[0]
    assert match.start_error_s == -5.0
    assert match.end_error_s == -3.0
    assert match.duration_error_s == 2.0
    assert match.overlap_s == 55.0
    assert result.match_rate == 1.0


def test_parse_and_compare_aer_samples_for_nadir_geometry() -> None:
    window = _window()
    report = parse_stk_aer_report(
        """Time (UTCG),Azimuth (deg),Elevation (deg),Range (km)
16 Jul 2026 12:00:00,0,90,500
16 Jul 2026 12:01:00,0,90,500
"""
    )
    result = compare_aer_samples(
        (window,),
        report.samples,
        geometry=PointGeometry(coordinates=(0.0, 0.0)),
        time_tolerance_s=1.0,
    )

    assert len(result.matched) == 2
    assert result.elevation_error_statistics_deg.mean_absolute_error < 1e-6
    assert result.range_error_statistics_km.mean_absolute_error < 1e-6


def test_validation_bundle_contains_reproducible_inputs() -> None:
    mode = next(
        mode
        for mode in ICEYE_PUBLIC_PROFILE.sensor.imaging_modes
        if mode.mode_id == "MODE-SAR-ICEYE-SPOT"
    )
    payload = build_stk_validation_bundle(
        request=_request(),
        satellite=_satellite(),
        mode=mode,
        windows=(_window(),),
        propagation_step_s=30.0,
    )

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        names = set(archive.namelist())
        assert "manifest.json" in names
        assert "satellite_omm.json" in names
        assert "target.geojson" in names
        assert "model_access_windows.csv" in names
        assert "STK_VALIDATION_INSTRUCTIONS.txt" in names
        manifest = json.loads(archive.read("manifest.json"))
        assert manifest["schema"] == "satplan.stk_validation_case.v1"
        assert manifest["satellite"]["slot_id"] == "SAR-01"
